### ISSUE TITLE
Reminder: See if we can have it work with spaces in the LP

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/fivem-integrations#50] opened 2022-11-29 23:53 UTC
Just a reminder about checking out if we can make it work with spaces.

**Comment by Dev-CasperTheGhost** [comment] 2022-11-30 14:30
This has been fixed in the latest script release, and on `main` of SnailyCADv4. Make sure to update both before verifying if it was fixed. I was unable to reproduce this issue. Feel free to re-open if it still occurs :)

**Closed by Dev-CasperTheGhost** 2022-11-30 14:30 UTC
